new-gog-wrapper: add argument for template path
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/new-gog-wrapper b/new-gog-wrapper
--- a/new-gog-wrapper
+++ b/new-gog-wrapper
@@ -5,8 +5,45 @@ locate_app_by_id () {
 }
 
 usage () {
-    echo >&2 "${0##*/} WRAPPER_PATH [WRAPPER_NAME]"
+    echo >&2 "Usage: ${0##*/} [-t TEMPLATE_PATH] WRAPPER_PATH [WRAPPER_NAME]"
     exit 2
+}
+
+process_arguments () {
+    template=
+
+    while getopts t:h opt; do
+        case "$opt" in
+            t)
+                template="$OPTARG"
+                if [ ! -e "$template" ]; then
+                    echo >&2 "Error: template path '$template' does not exist"
+                    usage
+                fi
+                ;;
+            h|\?)
+                usage
+                ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    if [ $# -eq 0 ] || [ $# -gt 2 ]; then
+        echo >&2 "Error: incorrect number of arguments"
+        usage
+    fi
+
+    wrapper_path="$1"
+    if [ -e "$wrapper_path" ]; then
+        echo >&2 "Error: $wrapper_path already exists"
+        exit 1
+    fi
+
+    if [ $# -eq 2 ]; then
+        wrapper_name="$2"
+    else
+        wrapper_name="$(basename "$wrapper_path" | sed -e "s/\.app$//")"
+    fi
 }
 
 plist_set () {
@@ -14,39 +51,24 @@ plist_set () {
 }
 
 
-if [ $# -eq 0 ] || [ $# -gt 2 ]; then
-    usage
-fi
-
 set -e
 
 scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
 PATH="$scriptdir:$PATH"
 
-if [ $# -eq 0 ]; then
-    usage
-fi
+process_arguments "$@"
 
-wrapper_path="$1"
-if [ -e "$wrapper_path" ]; then
-    echo >&2 "Error: $wrapper_path already exists"
-    exit 1
-fi
-
-if [ $# -eq 2 ]; then
-    wrapper_name="$2"
-else
-    wrapper_name="$(basename "$wrapper_path" | sed -e "s/\.app$//")"
-fi
-
-template="$(locate_app_by_id "org.kergoth.gog.GOG Galaxy for Windows" | head -n 1)"
 if [ -z "$template" ]; then
-    template="$(locate_app_by_id "GOG Galaxy for Windows.Wineskin.prefs" | head -n 1)"
+    template="$(locate_app_by_id "org.kergoth.gog.GOG Galaxy for Windows" | head -n 1)"
     if [ -z "$template" ]; then
-        echo >&2 "Error: unable to locate 'GOG Galaxy for Windows.app'"
-        exit 2
+        template="$(locate_app_by_id "GOG Galaxy for Windows.Wineskin.prefs" | head -n 1)"
+        if [ -z "$template" ]; then
+            echo >&2 "Error: unable to locate 'GOG Galaxy for Windows.app'"
+            exit 2
+        fi
     fi
 fi
+echo >&2 "Template: $template"
 cp -a "$template" "$wrapper_path"
 plist_set CFBundleIdentifier "org.kergoth.gog.$(printf "%s" "$wrapper_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')" "$wrapper_path"
 plist_set CFBundleName "$wrapper_name" "$wrapper_path"
