new-gog-wrapper: also check for the original wineskin id for template
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/new-gog-wrapper b/new-gog-wrapper
--- a/new-gog-wrapper
+++ b/new-gog-wrapper
@@ -40,6 +40,13 @@ else
 fi
 
 template="$(locate_app_by_id "org.kergoth.gog.GOG Galaxy for Windows" | head -n 1)"
+if [ -z "$template" ]; then
+    template="$(locate_app_by_id "GOG Galaxy for Windows.Wineskin.prefs" | head -n 1)"
+    if [ -z "$template" ]; then
+        echo >&2 "Error: unable to locate 'GOG Galaxy for Windows.app'"
+        exit 2
+    fi
+fi
 cp -a "$template" "$wrapper_path"
 plist_set CFBundleIdentifier "org.kergoth.gog.$(printf "%s" "$wrapper_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')" "$wrapper_path"
 plist_set CFBundleName "$wrapper_name" "$wrapper_path"
