wrap-native: split out separate scripts
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/wrap-native b/wrap-native
--- a/wrap-native
+++ b/wrap-native
@@ -1,8 +1,6 @@
 #!/bin/bash
 #
 # TODO: consider symlinking the icon rather than copying
-# TODO: obey goggame-*.info for the dosbox launcher configurations
-# TODO: populate BXHelpLinks with links from the goggame info
 
 set -e
 
@@ -31,8 +29,8 @@ usage () {
 }
 
 process_arguments () {
-    # Flashback is excluded, as REminiscence doesn't handle game controllers
-    excluded_game_types="flashback"
+    # flashback is excluded, as REminiscence doesn't handle game controllers
+    available_game_types="openmw gemrb openrct2 scummvm boxer-standalone"
     scummvm_game_id=
     new_game=
     dry_run=0
@@ -84,7 +82,7 @@ process_arguments () {
             _game="$game"
             if [ -e "$game/Contents/MacOS/GOGLauncher" ]; then
                 wrapped_game="$(find "$game/Contents/Resources/game" -type d -maxdepth 1 -mindepth 1)"
-                if [ -n "$wrapped_game" ] && [ -e "$wrapped_game/Wineskin.app" ]; then
+                if [ -n "$wrapped_game" ]; then
                     _game="$wrapped_game"
                 fi
             fi
@@ -111,116 +109,51 @@ process_arguments () {
     game_name="${game_base%.app}"
 }
 
-plist_set () {
-    pb -c "Set '$(pb_escape_value "$1")' '$(pb_escape_value "$2")'" "$3"
-}
-
-plist_add () {
-    pb -c "Add '$(pb_escape_value "$1")' '${4:-string}' '$(pb_escape_value "$2")'" "$3"
-}
-
-pb () {
-    PlistBuddy "$@"
-}
-
-pb_escape_value () {
-    printf "%s" "$1" | sed "s/'/\\\\'/g"
-}
-
 game_type_from_dir () {
     local game_type
-    local scummvm_game_id
 
-    case "$game_name" in
-        *Incredible\ Machine*)
-            scummvm_game_id=
-            ;;
-        *)
-            if [ "$game_name" = "King's Quest 7 - The Princeless Bride" ] || \
-               [ "$game_name" = "Police Quest - SWAT" ] || \
-               [ "$game_name" = "Quest for Glory 4 - Shadows of Darkness" ] || \
-               [ "$game_name" = "Roberta Williams' Phantasmagoria" ] || \
-               [ "$game_name" = "Space Quest 6 - Roger Wilco in the Spinal Frontier" ] || \
-               [ "$game_name" = "Betrayal at Krondor" ] || \
-               [ -n "$(find "$1"/ -iname gk1.gog)" ] || \
-               [ -n "$(find "$1"/ -iname gk2dos.bat)" ] || \
-               [ -n "$(find "$1"/ -iname express.exe)" ] || \
-               [ -n "$(find "$1"/ -iname torin.exe)" ] ; then
-                # Unsupported by scummvm
-                scummvm_game_id=
-            else
-                scummvm_game_id=$(get_scummvm_game_id "$game_name" "$game_dir") || true
-                case "$scummvm_game_id" in
-                    kq1*|kq4*|pq1*|sq1*)
-                        scummvm_game_id="${scummvm_game_id%sci}"
-                        if [ -n "$(find "$game_dir/" -iname "resource.map" -maxdepth 1)" ]; then
-                            scummvm_game_id="${scummvm_game_id}sci"
-                        fi
-                        ;;
-                    qfg1*)
-                        scummvm_game_id="${scummvm_game_id%vga}"
-                        if [ -n "$(find "$game_dir/" -iname "resource.map" -maxdepth 1)" ]; then
-                            scummvm_game_id="${scummvm_game_id}vga"
-                        fi
-                        ;;
-                esac
-            fi
-            ;;
-    esac
-
-
-    if [ -n "$scummvm_game_id" ]; then
-        game_type=scummvm
-    else
-        if [ -n "$(find "$1"/ -iname dosbox.exe -o -iname dos4gw.exe)" ]; then
-            game_type=dosbox
-        elif [ -n "$(find "$1"/ -iname scummvm.exe)" ]; then
-            game_type=scummvm
-        elif [ -n "$(find "$1"/ -iname rct2.exe -maxdepth 1)" ]; then
-            game_type=openrct2
-        elif [ -n "$(find "$1"/ -iname baldur.exe -maxdepth 1)" ] || \
-             [ -n "$(find "$1"/ -iname bgmain.exe -maxdepth 1)" ] || \
-             [ -n "$(find "$1"/ -iname torment.exe -maxdepth 1)" ]; then
-            game_type=gemrb
-        elif [ -e "$1/Morrowind.exe" ]; then
-            game_type=openmw
-        elif [ -e "$1/scripts.zfs" ]; then
-            # ZGI
-            game_type=scummvm
-            scummvm_game_id=zgi
-        elif wrap-flashback -c "$1" /invalid; then
-            game_type=flashback
+    for check_type in $available_game_types; do
+        if external_wrapper_check "$check_type"; then
+            game_type="$check_type"
+            break
         fi
-    fi
-    case "$game_type" in
-        "$excluded_game_types")
-            return
-    esac
-    printf '%s\t%s\n' "$game_type" "$scummvm_game_id"
+    done
+
+    echo "$game_type"
 }
 
-create_flashback_wrapper () {
+external_wrapper_check () {
+    evalf 'wrap-%s -c "%s"' "$1" "$game_dir" >/dev/null 2>&1
+}
+
+create_wrapper () {
     destdir="$1"
-    rmdir "$destdir"
-    wrap-flashback -n "$game_dir" "$destdir"
+    shift
+    evalf 'wrap-%s -n %s "%s" "%s"' "$game_type" "$*" "$game_dir" "$destdir"
     wrap_app "$game" "$destdir" -V
-    app_set_metadata -i com.kergoth.wrapped.flashback "$destdir"
+    app_set_metadata -i "com.kergoth.wrapped.$game_type.$(adjust_identifier "$game_name")" "$destdir"
 }
 
-adjust_identifier () {
-    printf "%s\n" "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' _
+evalf () {
+    fmt="$1"
+    shift
+    # printf >&2 "evalf: $fmt\n" "$@"
+    # eval echo >&2 "evalf: $(printf "$fmt" "$@")"
+    eval "$(printf "$fmt" "$@")"
 }
 
 wrap_app () {
     from="$1"
     to="$2"
     shift 2
+
     if [ $copy_wrapper -eq 1 ]; then
         wrap-app -n "$@" "$from" "$to"
         cp -a "$from" "$to/Contents/Resources/"
     else
         wrap-app "$@" "$from" "$to"
     fi
+
     # Sanity check
     if [ ! -e "$destdir/Contents/Resources/$game_base" ]; then
         echo >&2 "Game doesn't exist in $destdir, aborting"
@@ -270,336 +203,12 @@ END
     copymacicon "$1/Contents/Resources/$game_base" "$new_app"
 }
 
-locate_app_by_name () {
-    mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemDisplayName == '$*'"
-}
-
-locate_app_by_id () {
-    mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == '$*'"
-}
-
-create_dosbox_wrapper () {
-    destdir="$1"
-    boxer="$destdir/Contents/Resources/$game_name.boxer"
-    wrapper_template="$(locate_app_by_id net.washboardabs.boxer-standalone | head -n 1)"
-    identifier="org.kergoth.gog.boxer.$(adjust_identifier "$game_name")"
-
-    cp -a "$wrapper_template/." "$destdir/"
-    sed -i.bak -Ee "s/{{GAMEBOX_NAME}}/$game_name.boxer/; s/{{ORGANIZATION_NAME}}/kergoth@gmail.com/; s/{{ORGANIZATION_URL}}/mailto:kergoth@gmail.com/; s/{{BUNDLE_IDENTIFIER}}/$identifier/g; s/{{APPLICATION_NAME}}/$game_name/; s/{{YEAR}}/$(date +%Y)/;" "$destdir/Contents/Info.plist"
-    rm -f "$destdir/Contents/Info.plist.bak"
-    for i in UTImportedTypeDeclarations UTExportedTypeDeclarations CFBundleDocumentTypes; do
-        pb -c "Delete :$i" "$destdir/Contents/Info.plist"
-    done
-
-    wrap_app "$game" "$destdir"
-    plist_set CFBundleIdentifier "org.kergoth.gog.boxer.$(adjust_identifier "$game_name")" "$destdir/Contents/Info.plist"
-
-    newgame="$destdir/Contents/Resources/$game_base"
-    newgamedir="$(cd "$newgame/${game_dir#$game/}" && pwd -P)"
-
-    create_boxer "$boxer" "$newgamedir"
-
-    mv "$newgamedir" "$boxer/C.harddisk"
-    lnr "$boxer/C.harddisk" "$newgamedir"
-    find "$boxer/C.harddisk/" -iname \*.pdf | while read pdf; do
-        lnr "$pdf" "$boxer/Documentation/${pdf##*/}"
-    done
-}
-
-boxer_identifier_prefix=com.kergoth.boxer
-scummvm_identifier_prefix=com.kergoth.scummvm
-create_boxer () {
-    boxer="$1"
-    local game_dir="$2"
-    mkdir -p "$boxer"
-    mkdir -p "$boxer/Documentation"
-
-    plist_add BXGameIdentifier "$identifier" "$boxer/Game Info.plist"
-    pb -c "Add BXGameIdentifierType integer 3" "$boxer/Game Info.plist"
-    pb -c "Add BXLaunchers array" "$boxer/Game Info.plist"
-
-    # If there's one dosbox*.conf, use it.
-    # If there's multiple with autoexec directives, create bxlauncher
-    # configurations for each.
-    # If there's multiple and one is _single.conf, make it default
-    # If there's one dosbox .conf without autoexec, concatenate it to the
-    # others, as it has the generic configuration
-    find "$game_dir/" -iname dosbox\*.conf >"$boxer.dosboxes"
-    if [ $(wc -l <"$boxer.dosboxes") -eq 0 ]; then
-        echo >&2 "Error: no dosbox configuration found, aborting"
-        return 1
-    elif [ $(wc -l <"$boxer.dosboxes") -eq 0 ]; then
-        echo >&2 "One dosbox configuration found, using it"
-    fi
-
-    cat <<END >"$boxer/exec.sed"
-/^\[autoexec\]/{
-:s
-n
-/^mount C/b s
-p
-b s
-}
-END
-
-    no_autoexecs=
-    autoexecs=
-    while read conf; do
-        conf="${conf#$game_dir/}"
-        conf="${conf#/}"
-        if grep -q '^\[autoexec\]' "$game_dir/$conf"; then
-            autoexecs="$autoexecs $conf"
-            echo >&2 "Autoexec conf: $conf"
-        else
-            no_autoexecs="$no_autoexecs $conf"
-            echo >&2 "No autoexec conf: $conf"
-        fi
-    done <"$boxer.dosboxes"
-    rm -f "$boxer.dosboxes"
-
-    if [ -n "$no_autoexecs" ]; then
-        >"$boxer/DOSBox Preferences.conf"
-        for noauto in $no_autoexecs; do
-            cat "$game_dir/$noauto" >>"$boxer/DOSBox Preferences.conf"
-        done
-    fi
-
-    prefix="$(common_prefix $autoexecs)"
-    count=0
-    for autoexec_conf in $autoexecs; do
-        if [ $(echo $autoexecs | wc -w) -eq 1 ]; then
-            name=
-            launch="bxlaunch.bat"
-            title="$game_name"
-        else
-            name="$autoexec_conf"
-            if [ -n "$prefix" ]; then
-                name="${name#$prefix}"
-            fi
-            name="${name##*/}"
-            name="${name%.conf}"
-            name="${name#dosbox}"
-            name="${name#_}"
-            launch="bxlaunch_$name.bat"
-            title="$game_name ($name)"
-        fi
-
-        sed -ne '/^\[autoexec\]/q; p' "$game_dir/$autoexec_conf" >>"$boxer/DOSBox Preferences.conf"
-
-        pb -c "Add BXLaunchers:$count dict" "$boxer/Game Info.plist"
-        plist_add "BXLaunchers:$count:BXLauncherPath" "C.harddisk/$launch" "$boxer/Game Info.plist"
-        plist_add "BXLaunchers:$count:BXLauncherTitle" "$title" "$boxer/Game Info.plist"
-
-        conf_dir="$(dirname "$autoexec_conf")"
-        >"$game_dir/$launch"
-        if [ -n "$conf_dir" ] && [ "$conf_dir" != . ]; then
-            echo "cd $conf_dir" >>"$game_dir/$launch"
-        fi
-        LC_ALL=C sed -n -f "$boxer/exec.sed" "$game_dir/$autoexec_conf" >>"$game_dir/$launch"
-
-        count="$(($count + 1))"
-    done
-    rm -f "$boxer/exec.sed"
-}
-
-common_prefix () {
-    python -c "import os, sys; print(os.path.commonprefix(sys.argv[1:]))" "$@"
+adjust_identifier () {
+    printf "%s\n" "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' _
 }
 
 relpath () {
     python -c "import os, sys; print(os.path.relpath(*sys.argv[1:]))" "$@"
-}
-
-create_openmw_wrapper () {
-    destdir="$1"
-    openmw="$(locate_app_by_name "OpenMW" | sed 's,$,/Contents/MacOS/OpenMW,' | nlxargs ls -t | head -n 1 | sed 's,/Contents/MacOS/OpenMW,,')"
-    if [ -z "$openmw" ]; then
-        echo >&2 "Error: unable to locate OpenMW, please make it available."
-        return 1
-    fi
-    echo >&2 "OpenMW: $openmw"
-
-    openmw_dir="$(dirname "$openmw")"
-    openmw_version="$(pb -c 'Print :CFBundleVersion' "$openmw/Contents/Info.plist")"
-    openmw_base="OpenMW"
-    if [ -n "$openmw_version" ]; then
-        openmw_base="$openmw_base - $openmw_version"
-    fi
-    identifier="org.kergoth.openmw.$(adjust_identifier "$game_name")"
-    version="$openmw_base"
-
-    rm -rf "$destdir"
-    new-app -fr "$openmw_dir" "$destdir"
-    mv "$destdir.app" "$destdir"
-    if [ "$(basename "$openmw_dir")" != "$openmw_base" ]; then
-        mv "$destdir/Contents/Resources/$(basename "$openmw_dir")" "$destdir/Contents/Resources/$openmw_base"
-    fi
-
-    wrap_app "$game" "$destdir"
-    plist_set CFBundleIdentifier "$identifier" "$destdir/Contents/Info.plist"
-    plist_set CFBundleVersion "$version" "$destdir/Contents/Info.plist"
-
-    rm -rf "$destdir/Contents/Resources/$openmw_base/data"
-    ln -s "../$(basename "$game")/Game/Data Files" "$destdir/Contents/Resources/$openmw_base/data"
-    ln -sf ../Morrowind.ini "$destdir/Contents/Resources/$openmw_base/data/"
-
-    cat <<END >"$destdir/Contents/MacOS/app"
-#!/bin/sh
-cd "\$(dirname "\$0")/../Resources"
-exec open -W "$openmw_base/$(basename "$openmw")" --args "\$@"
-END
-    chmod +x "$destdir/Contents/MacOS/app"
-}
-
-create_openrct2_wrapper () {
-    destdir="$1"
-    openrct2="$(locate_app_by_id "website.openrct2.OpenRCT2" | sed 's,$,/Contents/MacOS/OpenRCT2,' | nlxargs ls -t | head -n 1 | sed 's,/Contents/MacOS/OpenRCT2,,')"
-    if [ -z "$openrct2" ]; then
-        echo >&2 "Error: unable to locate OpenRCT2, please make it available."
-        return 1
-    fi
-    echo >&2 "OpenRCT2: $openrct2"
-
-    rm -rf "$destdir"
-    new-app -f "$destdir"
-    mv "$destdir.app" "$destdir"
-
-    cp -a "$openrct2" "$destdir/"
-    wrap_app "$game" "$destdir"
-
-    newgame="$destdir/Contents/Resources/$game_base"
-    gamedir="$newgame/$(readlink "$newgame/Game")"
-    rm -f "$destdir/Game"
-    mv "$gamedir" "$destdir/Game"
-    lnr "$destdir/Game" "$gamedir"
-
-    identifier="org.kergoth.openrct2.$(adjust_identifier "$game_name")"
-    plist_set CFBundleIdentifier "$identifier" "$destdir/Contents/Info.plist"
-
-    cat <<END >"$destdir/Contents/MacOS/app"
-#!/bin/sh
-cd "\$(dirname "\$0")/../.."
-./OpenRCT2.app/Contents/MacOS/OpenRCT2 set-rct2 Game
-exec ./OpenRCT2.app/Contents/MacOS/OpenRCT2 "\$@"
-END
-    chmod +x "$destdir/Contents/MacOS/app"
-}
-
-create_gemrb_wrapper () {
-    destdir="$1"
-    gemrb="$(locate_app_by_id "net.sourceforge.gemrb" | sed 's,$,/Contents/MacOS/GemRB,' | nlxargs ls -t | head -n 1 | sed 's,/Contents/MacOS/GemRB,,')"
-    if [ -z "$gemrb" ]; then
-        echo >&2 "Error: unable to locate GemRB, please make it available."
-        return 1
-    fi
-    gemrb_base="${gemrb##*/}"
-    gemrb_version="$(pb -c 'Print CFBundleShortVersionString' "$gemrb/Contents/Info.plist")"
-    echo >&2 "GemRB: $gemrb"
-
-    rm -rf "$destdir"
-    new-app -f "$destdir"
-    mv "$destdir.app" "$destdir"
-
-    cp -a "$gemrb" "$destdir/Contents/Resources/"
-    wrap_app "$game" "$destdir"
-    newgame="$destdir/Contents/Resources/$game_base"
-    rel_game_dir="${game_dir#$game/}"
-    echo rel_game_dir: $rel_game_dir
-    rm -f "$destdir/Contents/Resources/game"
-    ln -s "$game_base/$rel_game_dir" "$destdir/Contents/Resources/game"
-
-    ln -s "Contents/Resources/$gemrb_base" "$destdir/GemRB.app"
-
-    identifier="org.kergoth.gemrb.$(adjust_identifier "$game_name")"
-    plist_set CFBundleIdentifier "$identifier" "$destdir/Contents/Info.plist"
-    # TODO: set gemrb wrapper version from game version + gemrb version
-
-    cat <<END >"$destdir/Contents/MacOS/app"
-#!/bin/sh
-cd "\$(dirname "\$0")/../Resources"
-exec "./$gemrb_base/Contents/MacOS/GemRB" game
-END
-    chmod +x "$destdir/Contents/MacOS/app"
-}
-
-create_scummvm_wrapper () {
-    destdir="$1"
-
-    if [ -z "$scummvm_game_id" ]; then
-        scummvm_game_id=$(get_scummvm_game_id "$game_name" "$game_dir") || true
-        if [ -z "$scummvm_game_id" ]; then
-            echo >&2 "Error: unknown scummvm game id, please specify"
-            return 1
-        fi
-    fi
-
-    case "$scummvm_game_id" in
-        agi|sci)
-            echo >&2 "Error: use of generic game id '$scummvm_game_id' for '$game'"
-            return 2
-            ;;
-    esac
-
-    cp -a "$scummvm_wrapper_template/." "$destdir/"
-
-    wrap_app "$game" "$destdir"
-    plist_set CFBundleIdentifier "org.kergoth.gog.scummvm.$(adjust_identifier "$game_name")" "$destdir/Contents/Info.plist"
-    plist_set CFBundleName "$scummvm_game_id" "$destdir/Contents/Info.plist"
-
-    rm -rf "$destdir/Contents/Resources/game"
-    ln -s "$game_base/Game" "$destdir/Contents/Resources/game"
-
-    case "$scummvm_game_id" in
-        zgi)
-            curl -s https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz | \
-                ( cd "$destdir/Contents/Resources" && tar -zx --strip-components=1 -f - )
-
-            # This game runs in a resolution such that advmame3x won't work
-            plist_set SVWGFXMode 1x "$destdir/Contents/Info.plist"
-            ;;
-    esac
-    case "$game_name" in
-        "King's Quest 7 - The Princeless Bride")
-            plist_set SVWGFXMode 1x "$destdir/Contents/Info.plist"
-            ;;
-        "Police Quest - SWAT")
-            plist_set SVWGFXMode 1x "$destdir/Contents/Info.plist"
-            ;;
-    esac
-}
-
-get_scummvm_game_id () {
-    _game="$1"
-    _directory="$2"
-    scummvm_game_id_name="$(echo "$_game" | sed 's/ - /: /')"
-    scummvm_game_id="$(grep -i "   *$scummvm_game_id_name\$" <"$scummvm_wrapper_template/Contents/Resources/GameIDs.txt" <"$scriptdir/Extra_GameIDs.txt" | sed -n "s#^\([^ ]*\).*#\1#p" | head -n 1)"
-    if [ -z "$scummvm_game_id" ]; then
-        vol=$(find "$_directory/" -iname object -maxdepth 1)
-        if [ -e "$vol" ]; then
-            echo >&2 "Assuming AGI engine"
-            scummvm_game_id=agi
-        fi
-
-        resource=$(find "$_directory/" -iname "resource.map" -maxdepth 1)
-        if [ -e "$resource" ]; then
-            echo >&2 "Assuming SCI engine"
-            scummvm_game_id=sci
-        fi
-
-        mapped=$(scummvm_game_id_map | sed -n "s#^\([^ ]*\) *$scummvm_game_id_name\$#\1#p")
-        if [ -n "$mapped" ]; then
-            scummvm_game_id=$mapped
-        fi
-    fi
-    echo $scummvm_game_id
-}
-
-scummvm_game_id_map () {
-    cat <<END
-t7g     The 7th Guest
-rtz-cd  Return to Zork
-END
-#dreamweb-cd-us Dreamweb
 }
 
 
@@ -611,19 +220,12 @@ process_arguments "$@"
 printf 'Game: %s\n' "$game"
 printf 'Game dir: %s\n' "$game_dir"
 
-scummvm_wrapper_template="$(locate_app_by_id com.dotalux.scummwrapper.svwlauncher | sed 's,$,/Contents/MacOS/scummvm,' | nlxargs ls -t | head -n 1 | sed 's,/Contents/MacOS/scummvm$,,')"
 if [ -z "$game_type" ]; then
-    game_type_info="$(game_type_from_dir "$game_dir")"
-    game_type="$(echo "$game_type_info" | cut -d"	" -f1)"
+    game_type="$(game_type_from_dir "$game_dir")"
     if [ -z "$game_type" ]; then
-            echo >&2 "Error: unknown game type for $game, please specify"
-            exit 3
+        echo >&2 "Error: unknown game type for $game, please specify"
+        exit 3
     fi
-    if [ -z "$scummvm_game_id" ]; then
-        scummvm_game_id="$(echo "$game_type_info" | cut -d"	" -f2)"
-    fi
-elif [ "$game_type" = "scummvm" ]; then
-    scummvm_game_id=$(get_scummvm_game_id "$game_name" "$game_dir") || true
 fi
 printf 'Game type: %s\n' "$game_type"
 
@@ -639,10 +241,6 @@ if [ $copy_wrapper -eq 1 ]; then
 fi
 
 printf 'New Game Path: %s\n' "$new_game"
-if [ -n "$scummvm_game_id" ]; then
-    printf 'ScummVM Game ID: %s\n' "$scummvm_game_id"
-fi
-
 
 if [ $dry_run -eq 1 ]; then
     exit 0
@@ -652,9 +250,18 @@ tmp="$(mktemp -d "${0##*/}.XXXXXX")"
 trap 'if [ ! -e "$game" ] && [ -e "$tmp_game/Contents/Resources/$game_base" ]; then mv "$tmp_game/Contents/Resources/$game_base" "$game"; fi; rm -rf "$tmp"' EXIT INT TERM
 tmp_game="$tmp/$new_game"
 
-eval 'create_${game_type}_wrapper "$tmp_game"'
+shift $#
+if [ -n "$scummvm_game_id" ]; then
+    game_type=scummvm
+    set -- -i "$scummvm_game_id"
+fi
+
+create_wrapper "$tmp_game" "$@"
 if [ ! -e "$tmp_game/Game" ] && [ ! -L "$tmp_game/Game" ]; then
     ln -s "Contents/Resources/$game_base/$(relpath "$game_dir" "$game")" "$tmp_game/Game"
+fi
+if [ -e "$tmp_game/finalize_wrapper" ]; then
+    evalf '"%s/finalize_wrapper"' "$tmp_game"
 fi
 create_extra_app_wrappers "$tmp_game"
 if [ -e "$new_game" ]; then
