wrap-native: add error message for broken Game symlink
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/wrap-native b/wrap-native
--- a/wrap-native
+++ b/wrap-native
@@ -63,6 +63,7 @@ process_arguments () {
             if [ -d "$game/Game" ]; then
                 game_dir="$game/$(readlink "$game/Game")"
             else
+                echo >&2 "Error: Game symlink does not exist or is invalid"
                 usage
             fi
             ;;
