wrap-native: add GemRB support
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/wrap-native b/wrap-native
--- a/wrap-native
+++ b/wrap-native
@@ -167,6 +167,10 @@ game_type_from_dir () {
             game_type=scummvm
         elif [ -n "$(find "$1"/ -iname rct2.exe -maxdepth 1)" ]; then
             game_type=openrct2
+        elif [ -n "$(find "$1"/ -iname baldur.exe -maxdepth 1)" ] || \
+             [ -n "$(find "$1"/ -iname bgmain.exe -maxdepth 1)" ] || \
+             [ -n "$(find "$1"/ -iname torment.exe -maxdepth 1)" ]; then
+            game_type=gemrb
         elif [ -e "$1/Morrowind.exe" ]; then
             game_type=openmw
         elif [ -e "$1/scripts.zfs" ]; then
@@ -453,6 +457,47 @@ create_openrct2_wrapper () {
 cd "\$(dirname "\$0")/../.."
 ./OpenRCT2.app/Contents/MacOS/OpenRCT2 set-rct2 Game
 exec ./OpenRCT2.app/Contents/MacOS/OpenRCT2 "\$@"
+END
+    chmod +x "$destdir/Contents/MacOS/app"
+}
+
+create_gemrb_wrapper () {
+    destdir="$1"
+    gemrb="$(locate_app_by_id "net.sourceforge.gemrb" | sed 's,$,/Contents/MacOS/GemRB,' | nlxargs ls -t | head -n 1 | sed 's,/Contents/MacOS/GemRB,,')"
+    if [ -z "$gemrb" ]; then
+        echo >&2 "Error: unable to locate GemRB, please make it available."
+        return 1
+    fi
+    gemrb_base="${gemrb##*/}"
+    gemrb_version="$(pb -c 'Print CFBundleShortVersionString' "$gemrb/Contents/Info.plist")"
+    echo >&2 "GemRB: $gemrb"
+
+    rm -rf "$destdir"
+    new-app -f "$destdir"
+    mv "$destdir.app" "$destdir"
+
+    cp -a "$gemrb" "$destdir/Contents/Resources/"
+    wrap_app "$game" "$destdir"
+    newgame="$destdir/Contents/Resources/$game_base"
+    if [ ! -e "$newgame" ]; then
+        echo >&2 "Game doesn't exist in $destdir, aborting"
+        exit 12
+    fi
+    rel_game_dir="${game_dir#$game/}"
+    echo rel_game_dir: $rel_game_dir
+    rm -f "$destdir/Contents/Resources/game"
+    ln -s "$game_base/$rel_game_dir" "$destdir/Contents/Resources/game"
+
+    ln -s "Contents/Resources/$gemrb_base" "$destdir/GemRB.app"
+
+    identifier="org.kergoth.gemrb.$(adjust_identifier "$game_name")"
+    plist_set CFBundleIdentifier "$identifier" "$destdir/Contents/Info.plist"
+    # TODO: set gemrb wrapper version from game version + gemrb version
+
+    cat <<END >"$destdir/Contents/MacOS/app"
+#!/bin/sh
+cd "\$(dirname "\$0")/../Resources"
+exec "./$gemrb_base/Contents/MacOS/GemRB" game
 END
     chmod +x "$destdir/Contents/MacOS/app"
 }
