score-games: fall back from metacritic to imdb
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/backlog/score-games b/backlog/score-games
--- a/backlog/score-games
+++ b/backlog/score-games
@@ -1,8 +1,110 @@
-#!/bin/sh
+#!/bin/bash
+
+set -o pipefail
 
 if [ $# -eq 0 ]; then
     set -- [0-9]*
 fi
+
+get_metacritic_scores () {
+    local search_query="$1"
+    local toml="$2"
+    local write=0
+    local mc_game
+    mc_game="$(toml-get metacritic.game <"$toml" 2>/dev/null)"
+    if [ $? -ne 0 ]; then
+        mc_game="$(echo "$search_query" | tr "[:upper:] " "[:lower:]-")"
+        if ! http --check-status --ignore-stdin -h "$base_url/$mc_game" >/dev/null 2>&1; then
+            local mc_url
+            mc_url="$(critic_search "$search_query" | head -n 1)" || return 1
+            if [ -z "$mc_url" ]; then
+                # No search results found
+                mc_game="##invalid##"
+            else
+                mc_game="${mc_url#$base_url/}"
+                if [ "$mc_game" = "$mc_url" ]; then
+                    echo >&2 "Error: unrecognized metacritic url $mc_url for $mc_game"
+                    exit 1
+                fi
+            fi
+        fi
+        write=1
+    fi
+
+    local score
+    score="$(toml-get metacritic.score <"$toml" 2>/dev/null)"
+    local user_score
+    user_score="$(toml-get metacritic.user_score <"$toml" 2>/dev/null)"
+    if [ -z "$score" ] || [ -z "$user_score" ]; then
+        write=1
+        local scores
+        scores="$(critic_scores "$base_url/$mc_game")"
+        if [ -z "$scores" ]; then
+            score="0"
+            user_score="0.0"
+        else
+            score="$(echo "$scores" | cut -d"	" -f1)"
+            user_score="$(echo "$scores" | cut -d"	" -f2)"
+            if [ "$score" = "tbd" ]; then
+                score="0"
+            fi
+            if [ "$user_score" = "tbd" ] || [ -z "$user_score" ]; then
+                user_score="0.0"
+            fi
+        fi
+    fi
+
+    if [ $write -eq 1 ]; then
+        if ! toml-get metacritic <"$toml" >/dev/null 2>&1; then
+            echo '[metacritic]' >>"$toml"
+        fi
+        cat "$toml" | \
+            toml-set-string metacritic.game "$mc_game" | \
+            toml-set metacritic.score "$score" metacritic.user_score "$user_score" >"$toml.new" && \
+            mv "$toml.new" "$toml"
+    fi
+    printf "%d\t%s\t%d\t%s\n" "$write" "$mc_game" "$score" "$user_score"
+}
+
+get_imdb_rating () {
+    local search_query="$1"
+    local toml="$2"
+    local write=0
+    local game title_id rating
+    rating="$(toml-get imdb.rating <"$toml" 2>/dev/null)"
+    if [ -z "$rating" ]; then
+        write=1
+        local ratings_info
+        ratings_info="$("$scriptdir/imdb-game-ratings" "$search_query" 2>/dev/null | head -n 1)"
+        if [ $? -eq 0 ]; then
+            game="$(echo "$ratings_info" | cut -d"	" -f1)"
+            title_id="$(echo "$ratings_info" | cut -d"	" -f2)"
+            rating="$(echo "$ratings_info" | cut -d"	" -f3)"
+            if [ "$rating" = "-" ]; then
+                rating=0
+            fi
+        else
+            # No search results found
+            game="##invalid##"
+            title_id="##invalid##"
+            rating=0
+        fi
+    else
+        game="$(toml-get imdb.game <"$toml")"
+    fi
+
+    if [ $write -eq 1 ]; then
+        if ! toml-get imdb <"$toml" >/dev/null 2>&1; then
+            echo '[imdb]' >>"$toml"
+        fi
+        cat "$toml" | \
+            toml-set-string imdb.game "$game" | \
+            toml-set-string imdb.title "$title_id" | \
+            toml-set imdb.rating "$rating" >"$toml.new" && \
+            mv "$toml.new" "$toml"
+    fi
+    printf "%d\t%s\t%s\n" "$write" "$game" "$rating"
+}
 
 critic_score () {
     http --check-status --ignore-stdin "$@" | pup '.metascore_anchor .metascore_w span text{}'
@@ -17,6 +119,8 @@ critic_search () {
     http --check-status --ignore-stdin "${metacritic_root}/search/game/$*/results" | pup 'a.col_left attr{href}' | sed "s,^,$metacritic_root," | sed -nE -e 's,(/game/pc/[^/]*)/?.*,\1,p'
 }
 
+
+scriptdir="$(dirname "$0")"
 quiet=0
 while getopts qh opt; do
     case "$opt" in
@@ -34,51 +138,21 @@ shift $((OPTIND - 1))
 
 base_url=http://www.metacritic.com/game/pc
 
-find "$@" -type l | while read game; do
+find "$@" -type l | while read -r game; do
     base="$(basename "$game" | sed 's,\.app$,,')"
-    search_query="$(echo "$base" | sed 's,(.*),,g; s,^[0-9.]* *- *,,;' | tr -d '[:punct:]' | sed 's,   *, ,g; s, $,,; s,^ ,,;')"
+    search_query="$(echo "$base" | sed 's,(.*),,g; s,\[.*\],,g; s,^[0-9.]* *- *,,;' | tr -d '[:punct:]' | sed 's,   *, ,g; s, $,,; s,^ ,,;')"
     toml="_metadata/$base.toml"
     touch "$toml"
 
-    write=0
-    mc_game="$(toml-get metacritic.game <"$toml" 2>/dev/null)"
-    if [ $? -ne 0 ]; then
-        mc_game="$(echo "$search_query" | tr "[:upper:] " "[:lower:]-")"
-        if ! http --check-status --ignore-stdin -h "$base_url/$mc_game" >/dev/null 2>&1; then
-            mc_url="$(critic_search "$search_query" | head -n 1)" || continue
-            if [ -z "$mc_url" ]; then
-                # No search results found
-                mc_game="##invalid##"
-            else
-                mc_game="${mc_url#$base_url/}"
-                if [ "$mc_game" = "$mc_url" ]; then
-                    echo >&2 "Error: unrecognized metacritic url $mc_url for $mc_game ($game)"
-                    exit 1
-                fi
-            fi
-        fi
-        write=1
-    fi
-
-    score="$(toml-get metacritic.score <"$toml" 2>/dev/null)"
-    user_score="$(toml-get metacritic.user_score <"$toml" 2>/dev/null)"
-    if [ -z "$score" ] || [ -z "$user_score" ]; then
-        write=1
-        scores="$(critic_scores "$base_url/$mc_game")"
-        if [ -z "$scores" ]; then
-            score="0"
-            user_score="0.0"
-        else
-            score="$(echo "$scores" | cut -d"	" -f1)"
-            user_score="$(echo "$scores" | cut -d"	" -f2)"
-            if [ "$score" = "tbd" ]; then
-                score="0"
-            fi
-            if [ "$user_score" = "tbd" ] || [ -z "$user_score" ]; then
-                user_score="0.0"
-            fi
-        fi
-        sleep 2
+    results="$(get_metacritic_scores "$search_query" "$toml")"
+    write="$(echo "$results" | cut -d"	" -f1)"
+    lookup_game="$(echo "$results" | cut -d"	" -f2)"
+    scores="$(echo "$results" | cut -d"	" -f3-)"
+    if [ "$scores" = "0	0.0" ]; then
+        results="$(get_imdb_rating "$search_query" "$toml")"
+        write="$(echo "$results" | cut -d"	" -f1)"
+        lookup_game="$(echo "$results" | cut -d"	" -f2)"
+        scores="$(echo "$results" | cut -d"	" -f3-)"
     fi
 
     if [ $quiet -eq 0 ] || [ $write -eq 1 ]; then
@@ -88,16 +162,9 @@ find "$@" -type l | while read game; do
         #         echo "$imdb_ratings"
         #     fi
         # fi
-        printf "%s -> %s: %s, %.1f\n" "$game" "$mc_game" "$score" "$user_score"
-    fi
-
-    if [ $write -eq 1 ]; then
-        if ! toml-get metacritic <"$toml" >/dev/null 2>&1; then
-            echo '[metacritic]' >>"$toml"
+        printf "%s -> %s: %s\n" "$game" "$lookup_game" "$scores"
+        if [ "$write" -eq 1 ]; then
+            sleep 2
         fi
-        cat "$toml" | \
-            toml-set-string metacritic.game "$mc_game" | \
-            toml-set metacritic.score "$score" metacritic.user_score "$user_score" >"$toml.new" && \
-            mv "$toml.new" "$toml"
     fi
 done
